server.port=8080
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_EWM_DATASOURCE_URL}
spring.datasource.username=${SPRING_EWM_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_EWM_DATASOURCE_PASSWORD}
stats-service.url=${STATS_SERVICE_URL}
main-service.name=${MAIN_SERVICE_NAME}