server.port=9090
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_STATS_DATASOURCE_URL}
spring.datasource.username=${SPRING_STATS_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_STATS_DATASOURCE_PASSWORD}